# Site settings
title: cutalion's sidenotes
email: cutalion@gmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://blg.ctln.pw" # the base hostname & protocol for your site
main_url: "http://ctln.pw"
twitter_username: cutalion
github_username:  cutalion

# Build settings
markdown: kramdown
